# Generated by Django 5.0 on 2023-12-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAuth", "0002_jobapplication_applicationdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                ("companyID", models.AutoField(primary_key=True, serialize=False)),
                ("companyName", models.CharField(max_length=255)),
                ("jobDescription", models.TextField()),
                ("jobLocation", models.CharField(max_length=255)),
                ("jobDeadline", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="jobID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userAuth.company"
            ),
        ),
        migrations.DeleteModel(
            name="jobs",
        ),
    ]
