# Generated by Django 5.0 on 2023-12-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAuth", "0005_remove_jobapplication_companyid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Applied", "Not Applied"),
                    ("Applied", "Applied"),
                    ("Interview", "Interview"),
                ],
                max_length=255,
            ),
        ),
    ]
