# Generated by Django 5.0 on 2023-12-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAuth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="applicationDate",
            field=models.DateField(default=None),
        ),
    ]
