# Generated by Django 5.0 on 2023-12-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAuth", "0004_rename_jobid_jobapplication_companyid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="companyID",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="companyName",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="jobDeadline",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="jobDescription",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="jobLocation",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[(-1, "Not Applied"), (0, "Applied"), (1, "Interview")],
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="company",
        ),
    ]
